name: 'add-linear-author-as-reviewer'
description: 'Add Linear author as reviewer'
author: 'Mergify'
inputs:
  LINEAR_API_KEY:
    required: true
    description: 'Linear Api Key'
  GITHUB_TOKEN:
    required: true
    description: 'GitHub Token'
  PULL_REQUEST_BODY:
    required: true
    description: 'Pull request body'
  EMAIL_MAPPING:
    required: true
    description: 'Linear Email to GitHub login mapping (one by line and separated by a space)'
runs:
  using: 'composite'
  steps:
    - id: extract
      shell: bash
      run: |
        python3 -m venv venv
        venv/bin/pip install httpx
        venv/bin/python ${{ github.action_path }}/linear-extract-reviewers.py
      env:
        INPUT_LINEAR_API_KEY: ${{ inputs.LINEAR_API_KEY }}
        INPUT_EMAIL_MAPPING: ${{ inputs.EMAIL_MAPPING }}
        INPUT_PULL_REQUEST_BODY: ${{ inputs.PULL_REQUEST_BODY }}
    - shell: bash
      if: "${{ steps.extract.outputs.creators }}"
      run: |
        for creator in ${{steps.extract.outputs.creators}}; do
          gh pr edit ${{github.event.pull_request.html_url}} --add-reviewer $creator
        done
      env:
        GITHUB_TOKEN: ${{inputs.GITHUB_TOKEN}}
